<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <Platforms>x64</Platforms>
    <UseWinUI>true</UseWinUI>
    <EnableMsixTooling>true</EnableMsixTooling>
    <PublishProfile>Properties\PublishProfiles\win10-$(Platform).pubxml</PublishProfile>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <AppxManifest Include="Package.appxmanifest" />
    <Content Include="Assets\Square44x44Logo.png" />
    <Content Include="Assets\Square150x150Logo.png" />
    <Content Include="Assets\StoreLogo.png" />
    <ProjectReference Include="../SecureKiosk.Core/SecureKiosk.Core.csproj" />
    <ProjectReference Include="../SecureKiosk.Infrastructure/SecureKiosk.Infrastructure.csproj" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.7.250401001" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.0" />
  </ItemGroup>
</Project>
